title: Devnauts
email: devnauts@outlook.com
greeting: Gianfranco Ureta
description: > # this means to ignore newlines until another tag
    — Front-end Developer
github:  devnauts
#linkedin: ezrasavard
favicon: favicon.png

# Build settings
paginate: 4
#baseurl: "/ezorademo" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "http://devnauts.github.io" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
gems: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

# cover images are expected to be 900px by 240px, or at least 15:4 aspect ratio
# thumbnails look best with 3:1 or 5:2 ratios in this layout.
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Gianfranco Ureta"
            cover: "/media/header.jpg"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Gianfranco Ureta"
            cover: "/media/header.jpg"
            layout: "default"